### ISSUE TITLE
Stop responding when terragrunt.hcl is listed as extra_atlantis_dependencies

### ISSUE THREAD

**Issue by kornik** [transcend-io/terragrunt-atlantis-config#230] opened 2022-06-08 10:57 UTC
During preparation to use `terragrunt-atlantis-config` I wrote a script to add `extra_atlanits_dependecies` from existing `atlantis.yaml` to `terragrunt.hcl` files. Script just read `when_modified` list from `atlantis.yaml` and add it as `extra_atlantis_dependecies` list.

After my changes `terragrunt-atlantis-config` just stoped working during execution (hang) without any errors. I found out the reason is `terragrunt.hcl` listed as `extra_atlanits_dependecies`. 

It should be handled by skipping that entry or throw an error.

**Comment by dmattia** [comment] 2022-07-06 21:13
Hey @kornik! I think this is a duplicate of https://github.com/transcend-io/terragrunt-atlantis-config/issues/191, it's just a shorter way to reach a dependency cycle, which this library doesn't support detecting quite yet.

**Closed by dmattia** 2022-07-06 21:13 UTC
