### ISSUE TITLE
panic: concurrent map writes

### ISSUE THREAD

**Issue by joshuawscott** [transcend-io/terragrunt-atlantis-config#227] opened 2022-05-18 17:51 UTC
terragrunt-atlantis-config Version: 0.13.0 and 0.14.2

We run this command to generate our atlantis.yaml:
```
terragrunt-atlantis-config generate --workflow terragrunt --autoplan --output atlantis.yaml --parallel=true --create-workspace --ignore-parent-terragrunt=false --num-executors=32 --filter='[^.]*/**'
```

When Atlantis runs it, we don't see any issues, but we also run the same command in Travis CI so we have an easy way to inspect the output in case we have unexpected results or syntax errors that prevent the generation from completing. Intermittently we get this output (truncated):

<details><summary>Stacktrace</summary>

```
time="2022-05-17T19:10:12Z" level=info msg="Could not find an old config file. Starting from scratch"
fatal error: concurrent map writes
fatal error: concurrent map writes
goroutine 40 [running]:
runtime.throw({0x11ff3e4, 0xc0011ea690})
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1198 +0x71 fp=0xc00102a548 sp=0xc00102a518 pc=0x433d91
runtime.mapassign_faststr(0x107f140, 0xc0004f85d0, {0xc00023cde0, 0x55})
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/map_faststr.go:294 +0x38b fp=0xc00102a5b0 sp=0xc00102a548 pc=0x412eab
github.com/gruntwork-io/terragrunt/config.sopsDecryptFile({0xc0007b0db0, 0x1, 0x1}, 0x1479e68, 0xc0000a0b40)
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/config_helpers.go:666 +0x2a5 fp=0xc00102a668 sp=0xc00102a5b0 pc=0xefd3a5
github.com/gruntwork-io/terragrunt/config.wrapStringSliceToStringAsFuncImpl.func1({0xc0008466a0, 0xc0001c9a8a, 0x100ea60}, {{0xc0007b0da0, 0xc000064800}})
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/cty_helpers.go:32 +0x5e fp=0xc00102a6d8 sp=0xc00102a668 pc=0xeff81e
github.com/zclconf/go-cty/cty/function.Function.Call({0x0}, {0xc0008466a0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.8.3/cty/function/function.go:295 +0x29a fp=0xc00102a928 sp=0xc00102a6d8 pc=0xb6f07a
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc000a08690, 0xc000339830)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.10.0/hclsyntax/expression.go:442 +0x249f fp=0xc00102bb70 sp=0xc00102a928 pc=0xbc839f
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc000a08780, 0xc000339830)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.10.0/hclsyntax/expression.go:408 +0x3827 fp=0xc00102cdb8 sp=0xc00102bb70 pc=0xbc9727
github.com/gruntwork-io/terragrunt/config.attemptEvaluateLocals(0xc0000a0b40, {0xc000041720, 0x4b}, {0xc0002a8260, 0x1, 0x100000000412baa}, 0xc0006e6510, 0xc0004f9290, {0xc0002a49f0, 0x3, ...}, ...)
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/locals.go:172 +0x604 fp=0xc00102cfd0 sp=0xc00102cdb8 pc=0xf0d724
github.com/gruntwork-io/terragrunt/config.evaluateLocalsBlock(0xc0000a0b40, 0x0, 0x0, {0xc000041720, 0x4b}, 0x3, {0xc0002a49f0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/locals.go:86 +0x465 fp=0xc00102d130 sp=0xc00102cfd0 pc=0xf0ce65
github.com/gruntwork-io/terragrunt/config.DecodeBaseBlocks(0x0, 0xc000eead80, 0xc000cb6360, {0xc000041720, 0x4b}, 0x0, {0xc0002a49f0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/config_partial.go:121 +0x10d fp=0xc00102d1c8 sp=0xc00102d130 pc=0xefe42d
github.com/gruntwork-io/terragrunt/config.PartialParseConfigString({0xc000eead80, 0x46a}, 0x0, 0xc000f59368, {0xc000041720, 0x4b}, {0xc0002a49f0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/config_partial.go:189 +0x109 fp=0xc00102d2e0 sp=0xc00102d1c8 pc=0xefe7c9
github.com/gruntwork-io/terragrunt/config.PartialParseConfigFile({0xc000041720, 0x4b}, 0x7fd3865715b8, 0x30, {0xc0002a49f0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/config_partial.go:151 +0x7f fp=0xc00102d348 sp=0xc00102d2e0 pc=0xefe61f
github.com/gruntwork-io/terragrunt/config.partialParseIncludedConfig(0x0, 0xc000ae21e0, {0xc0002a49f0, 0xbf, 0xc000f59460})
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/config_partial.go:340 +0x105 fp=0xc00102d3c0 sp=0xc00102d348 pc=0xeff3e5
github.com/gruntwork-io/terragrunt/config.handleIncludePartial(0xc00072f1d0, 0xc0006e50e0, 0xc0000a0b40, {0xc0002a49f0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/include.go:167 +0x192 fp=0xc00102d498 sp=0xc00102d3c0 pc=0xf08192
github.com/gruntwork-io/terragrunt/config.PartialParseConfigString({0xc0005fac80, 0x256}, 0xc000064800, 0xc0002a49f0, {0xc000046d20, 0x5e}, {0xc0002a49f0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/config_partial.go:318 +0xb45 fp=0xc00102d5b0 sp=0xc00102d498 pc=0xeff205
github.com/gruntwork-io/terragrunt/config.PartialParseConfigFile({0xc000046d20, 0x5e}, 0x203000, 0x0, {0xc0002a49f0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.1/config/config_partial.go:151 +0x7f fp=0xc00102d618 sp=0xc00102d5b0 pc=0xefe61f
github.com/transcend-io/terragrunt-atlantis-config/cmd.getDependencies.func1()
	/home/runner/work/terragrunt-atlantis-config/terragrunt-atlantis-config/cmd/generate.go:135 +0x187 fp=0xc00102dae8 sp=0xc00102d618 pc=0xf61a67
golang.org/x/sync/singleflight.(*Group).doCall.func2(0xc00102db3e, 0xc000fe2180, 0x60)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:193 +0x6f fp=0xc00102db20 sp=0xc00102dae8 pc=0xf6064f
golang.org/x/sync/singleflight.(*Group).doCall(0x107c6e0, 0xc0004f9e90, {0xc000046d20, 0x5e}, 0xf60e3d)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:195 +0xad fp=0xc00102db90 sp=0xc00102db20 pc=0xf6056d
golang.org/x/sync/singleflight.(*Group).Do(0x1d109d0, {0xc000046d20, 0x5e}, 0x87)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:108 +0x154 fp=0xc00102dbe0 sp=0xc00102db90 pc=0xf603b4
github.com/transcend-io/terragrunt-atlantis-config/cmd.getDependencies({0xc000046d20, 0x0}, 0x0)
	/home/runner/work/terragrunt-atlantis-config/terragrunt-atlantis-config/cmd/generate.go:111 +0x67 fp=0xc00102dc30 sp=0xc00102dbe0 pc=0xf61847
github.com/transcend-io/terragrunt-atlantis-config/cmd.createProject({0xc000046d20, 0x12})
	/home/runner/work/terragrunt-atlantis-config/terragrunt-atlantis-config/cmd/generate.go:306 +0xee fp=0xc00102de18 sp=0xc00102dc30 pc=0xf6346e
github.com/transcend-io/terragrunt-atlantis-config/cmd.main.func1()
	/home/runner/work/terragrunt-atlantis-config/terragrunt-atlantis-config/cmd/generate.go:712 +0xb7 fp=0xc00102df78 sp=0xc00102de18 pc=0xf66b97
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67 fp=0xc00102dfe0 sp=0xc00102df78 pc=0xeec847
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00102dfe8 sp=0xc00102dfe0 pc=0x464681
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```
</details>

The full stacktrace is here: https://gist.github.com/joshuawscott/dd5915bb98f904cdbf414f6a5e09689e

Possibly salient point, this is generating a config that contains 166 configs.

When running locally this happens in about 1 in 5 runs.

**Comment by dmattia** [comment] 2022-07-06 21:17
Oh interesting. Is there any chance you could find a minimal example setup that would cause this to happen relatively consistently? I haven't seen this in the repo we use it in

**Comment by WarpRat** [comment] 2022-07-18 04:59
We're seeing the same thing with a similarly sized config, maybe a bit larger. We tend to see it most often after there has been a plan or apply error in one of the workspaces. Our command is:
`terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace`
I've attempted to reliably reproduce it but can't seem to  get it to happen in a mock config. I can provide full stack traces if it's helpful but it's essentially the same as above. Hopefully I can come up with a more reliable way to reproduce this.

@joshuawscott - have you found any workaround for this? Since we don't have a way to prevent Atlantis from running if the pre workflow hook fails this has been extremely disruptive when it does pop up. We're doing some hacky bash scripting to retry a few times which seems to work but is definitely just a bandaid.

**Comment by joshuawscott** [comment] 2022-07-19 13:56
@WarpRat I haven't gotten any workaround. We basically just have to re-plan when it happens, which is maybe once/day.

We had a test where we were running terragrunt-atlantis-config in travis-ci, and we just set that to allow failure.

I'll see if I can get a minimal test case working.

**Comment by WarpRat** [comment] 2022-07-19 18:15
@joshuawscott - we are indeed. Great find. It seems likely that the resolution to #157 would likely fix this issue as well. I'm not sure when I'll have time but maybe I can pick up the WIP work in that issue. At least we have a good starting point to start poking around in the code. Thanks!

**Comment by alk-adong** [comment] 2022-11-08 08:33
Hello,

I hit this panic too and pushed a fix upstream to protect the sops cache from concurrent writes.

https://github.com/gruntwork-io/terragrunt/commit/4c20c2cef68a8fcb98208e5f815d342d2fe4fddb

Bumping the go.mod terragrunt version to the latest release should hopefully fix this.

**Comment by adongy** [comment] 2022-11-08 08:33
Hello,

I hit this panic too and pushed a fix upstream to protect the sops cache from concurrent writes.

https://github.com/gruntwork-io/terragrunt/commit/4c20c2cef68a8fcb98208e5f815d342d2fe4fddb

Bumping the go.mod terragrunt version to the latest release should hopefully fix this.

**Comment by Almenon** [comment] 2024-01-27 05:32
Closing, as https://github.com/transcend-io/terragrunt-atlantis-config/pull/297 has been merged in. Now terragrunt-atlantis-config uses [v0.54.1](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.54.1). The latest release (https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.17.3) should work now, theoretically.

**Closed by Almenon** 2024-01-27 05:32 UTC
